package:
  name: SAVU_Py
  version: 0.0.0.dev1

source:
  git_rev: 
  git_url: https://gitlab.com/ungersebastian/spectralanalysispack.git

requirements:
  build:
    - python
    - setuptools
    - IPython
  run:
    #- python
    - tifffile
    #- mock>=2.0
    #- IPython
test:
  imports:
    - SAVU_Py

about:
  home: https://gitlab.com/ungersebastian/spectralanalysispack.git
  license: GPL
  
